name: bushu
on:
  workflow_dispatch:
  schedule:
    - cron: '00 16 * * *' # UTC时间的16:00，对应中国时间8:00

jobs:
  bushu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use pyton
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.bushu/pip
          key: ${{ runner.os }}-bushu-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-bushu-
      - name: Install requirements
        run: |
          pip install -r ./requirements.txt
      - name: bushu
        run: python3 index.py
        env:
          USER_PHONE: ${{ secrets.XIAOMI_USER_PHONE }}
          USER_PWD: ${{ secrets.XIAOMI_USER_PWD }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          TX_QQ: ${{ secrets.QMSG_QQ }}
          SEND_KEY: ${{ secrets.QMSG_SEND_KEY }}
          # STEP: 10000
          STEP_MIN: 10000
          STEP_MAX: 30000
